savagegus/ansible-consul

templates/consul.json.j2

Don't know how I missed this, since the role ran fine on my local before I submitted the PR.

Missing quotes around encrypt

---

.kitchen.yml
templates/consul.json.j2
test/integration/acls/default.yml
test/integration/acls/serverspec/consul_spec.rb
test/integration/acls/serverspec/spec_helper.rb

Continuing to chip away at Issue #9

Adding support for ACLs configuration

---

defaults/main.yml
templates/consul.json.j2

I needed the ability to set Consul to run on different ports because we have internal applications that run on those ports.
Cc: @sudarkoff

Make it possible to customize ports

---

README.md

I :heart: colors.
See https://github.com/msabramo/ansible-consul/tree/patch-2#example-playbook for how it renders it in delicious coloriciousness.

README.md: Syntax highlight example playbook

---

handlers/main.yml

Fixing silly command typo

---

.kitchen.yml
Gemfile.lock
handlers/main.yml
tasks/dnsmasq.yml
test/integration/dns/serverspec/dnsmasq_spec.rb

Restric dnsmasq to loopback interface

---

.kitchen.yml
README.md
defaults/main.yml
handlers/main.yml
meta/main.yml
tasks/dnsmasq.yml
tasks/install-ui.yml
tasks/install.yml
tasks/service.yml
test/integration/custom_templates/default.yml
test/integration/custom_templates/serverspec/consul_custom_templates_spec.rb
test/integration/default/serverspec/consul_spec.rb
test/integration/dynamic_binding/serverspec/consul_dynamic_binding_spec.rb
test/integration/tls/serverspec/consul_tls_spec.rb
test/integration/tls_client/serverspec/consul_tls_client_spec.rb
test/templates/consul.systemd.j2

All tests are passing. There is not a TestKitchen suite around nginx config and consul ui install and config so pretty sure that it may be broken at this point.
I don't use the role in that capacity, so I don't feel particularly well positioned to build a decent test suite around it.

Centos 7 support

---

tasks/service.yml
templates/consul.json.j2

There is no `running` state according to doc https://docs.ansible.com/ansible/service_module.html

state fix (https://docs.ansible.com/ansible/service_module.html)

---

defaults/main.yml
templates/consul.json.j2

A starting point for setting dns_config. Not sure how custom service_ttl's could be handled, so I just allowed for the setting of a global service ttl.

add dns config options

---

README.md

you merged my last one so quick I didn't have time to get this in! :blush:

update README to include dns_config

---

templates/consul.json.j2

`consul_ui_dir` is mentioned in the docs but is not used where appropriate.

Respect `consul_ui_dir` setting.

---

templates/consul.json.j2

Fixed adding extra comma for last consul server in join loop

---

tasks/install-ui.yml

Installs UI files in the proper directory

Fixing #89

---

README.md
defaults/main.yml
templates/consul.json.j2

Templates out a few more configuration variables, mostly around retrying
joins and WAN connectivity.

Add retry join and WAN variables

---

README.md
defaults/main.yml
tasks/install.yml

Hy, 
I wanted to change the kv, config and add path templates, and I added to variables, because I think in this case it is easier to find them. 
Have a nice day.

Save the items to variable

---

tasks/install-cli.yml

This way the download only happens if it is changed.

Avoid needless downloads and rebuilds

---

README.md

Fix disable_update_check -> consul_disable_update_check from README. Forgot this from my last pull request.

Disable_update_check -> consul_disable_update_check

---

tasks/install.yml

Fixes savagegus/ansible-consul#146

Set owner/group of ~consul/.bashrc instead of becoming consul user

---

tasks/install-ui.yml

Use status field of ansible_selinux to detect SELinux

---

handlers/main.yml
tasks/install-ui.yml

Also add missing notify for nginx reload
Fixes issue #168

Override nginx reload handler defined in multiple dependencies

---

tasks/install.yml
templates/consul.conf.j2

Fixes savagegus/ansible-consul#78

Allow upstart to be used on non-Debian systems
