defaults/main.yml, tasks/install.yml, templates/consul.conf.j2, templates/consul.json.j2
I've been using your role for a couple of months now, it's solid work, thanks!
Here is a collection of things I've done to make it more useful for my use cases, and I thought you might want to talk about them.
The first thing I did was remove the default node name. I feel like this is safe because consul calculates a node name for you when it starts up, if you don't define one. In my use case, I have found myself *needing* that ;). 
We building AMIs as assets, and create instances using that AMI on demand in scaling groups. What that means is, when the machine is initially provisioned with this role, it creates a node name based on the hostname of the *build instance*. So, any future instance that is spun up using that AMI will be provisioned in consul with the *build instance* node name. …
=> Some (potentially) useful updates.

README.md
Added the ``consul_join_at_start`` variable to the variables section of the README.
Currently, the ``consul_servers`` variable isn't used if the the ``consul_join_at_start`` is either absent or false.
Not sure if the variable is in the right place in the variables list, though. The same goes for the way it's documented with the "empty value" ``~`` and note about no default value.
Hope it can help in some way at least :-)
=> Added information about the variable consul_join_at_start

templates/consul.conf.j2, test/integration/default/serverspec/consul_spec.rb
See https://groups.google.com/forum/#!topic/consul-tool/qewFEqgAoF8 for a discussion of why this is advisable.
Implementation shamelessly copied from: https://github.com/hashicorp/consul/blob/master/terraform/openstack/scripts/upstart.conf
=> Setting GOMAXPROCS to the number of processors on the host

README.md
`arm install savagegus.consul` works for me. What's there with `ansible-consul` doesn't.
=> README.md: Fix typo in `arm install` command

README.md, defaults/main.yml
because I tried out this role a few days ago and today a couple of my Ops guys were asking me why dnsmasq is installed on our test servers :-)
It's safer to not install extra packages.
=> consul_install_dnsmasq: false

tasks/install.yml, templates/consul.conf.j2, test/integration/default/serverspec/dnsmasq_spec.rb, test/integration/tls/serverspec/consul_tls_spec.rb
changes included;
- change consul to system account
- allow consul to open port 443 for https api
- include testing
=> when tls encryption and https api are enabled, consul user don't have permission to run consul https api on port 443

defaults/main.yml, handlers/main.yml, tasks/install.yml, templates/consul.systemd.j2
This pull request adds systemd functionality. An important breaking change to note is the requirement to specify consul_use_systemd OR consul_use_upstart for the role. This could be changed to defaulting to upstart to avoid a breaking change in role usage. Thoughts?
=> Added systemd service file and install logic.

README.md
Modifying example in README to use correct names for the Consul
client cert and trusted CA cert. Previously these were mismatched
which can lead to some confusion if you copy and paste (speaking from
experience).
=> Correcting error in README

README.md, defaults/main.yml, templates/consul.conf.j2, templates/consul.json.j2
when client_addr or -client is set to public IP http/https/rpc/dns
are bound to that IP. the normal consul command will fail without
adding additional parameter (-rpc-addr/-http-addr) as part of the command. 
this change will let you make fine grain adjustment to configure http(s) api to listen to public IP but remain rpc to listen to bind to localhost.
=> enabling http(s) api to bind to public IP and rpc to localhost

README.md, templates/consul.json.j2
This allows users to set `consul_statsd_address` to an address for statsd which Consul will send metrics to
=> Add statsd_addr support to Consul config

README.md, templates/consul.json.j2
This PR allows users to set the `statsite_address` and/or `statsite_prefix`.
This is a continuation of #59.
=> Add statsite support

defaults/main.yml, tasks/install.yml
repository to host the Consul download.
Default behavior of get_url when username and password are empty is to omit the Authorization header altogether.
=> Adding support for authentication when mirroring or using an artifact

tasks/dnsmasq.yml
when dnsmasq is enabled if no proper delay was in placed, succeeding job that uses dns fails. this allows dnsmasq to fully started before proceeding to the next step.
=> allow dnsmasq to restart fully

tasks/install-ui.yml, tasks/install.yml
Sorry for my bad English.
In Ansible 1.9.4 [get_url module](http://docs.ansible.com/ansible/get_url_module.html) always download files even if they already exists on disk (option --force=no does not work properly as specified in manual).
My propose is to check if the files already exists.
Now, when role was executed first time:
```
TASK: [savagegus.consul | check archive stat] ******************************
<192.168.0.2> REMOTE_MODULE stat path=/tmp/0.5.2_linux_amd64.zip
ok: [host] => {"changed": false, "stat": {"exists": false}}
TASK: [savagegus.consul | download consul] ************************************
<192.168.0.2> REMOTE_MODULE get_url url=https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip dest=/tmp ...
changed: [host] => {"changed": true, "checksum": "...", ......}
``` …
=> Download archives from web only if local files does not exists

defaults/main.yml, handlers/main.yml, meta/main.yml, tasks/dnsmasq.yml, tasks/install-ui.yml, tasks/install.yml, tasks/main.yml, tasks/service.yml
I'm happy I came across this repo- I recently had to add Consul support for Centos, and found this the best starting point. I'm new to Ansible, and had to make some semi-opinionated choices to get it working, but I wanted to put it out there in case you were interested.
* Add support for Centos
* Removed NGINX requirement for UI. The ```franklinkim.nginx``` doesn't exist on ansible-galaxy (I couldn't install as a req) nor did I need/want NGINX. Instead, the UI option just enables the UI, and I modified the NGINX support to do a config only, assuming NGINX is already installed. 
* Made Consulate optional (I didn't need this, and seemed to have some install issues)
* Added 127.0.0.1 to /etc/resolve.conf; otherwise, I couldn't get dnsmasq working out-of-box with consul.
Feedback appreciate, …
=> Adding Centos Support

meta/main.yml
I think those got broken in the Centos7 PR, my apologies.
=> Restoring proper metadata format

templates/consul.conf.j2
Due to using sudo, GOMAXPROCS was not being set in the consul environment.  Kept getting the following upon startup:
WARNING: It is highly recommended to set GOMAXPROCS higher than 1
=> Fix GOMAXPROCS setup

tasks/install.yml, templates/consul.conf.j2
1) Homedir in upstart script was fixed dir, made it parameter.
2) Set homedir to parameter when creating user.
=> fixed homedir locations

tasks/install-ui.yml, tasks/install.yml, templates/consul.json.j2
Added verify_server_hostname parameter.
"Previously, a compromised client could be restarted as a server and perform a MITM attack against the cluster. With this PR, TLS certs can be generated matching the pattern of 'server'"
https://github.com/hashicorp/consul/issues/792
=> added verify_server_hostname parameter

tasks/install.yml
If we set rpc address to something other than 127.0.0.1, consul command requires --rpc-addr flag or CONSUL_RPC_ADDR env variable. 
This PR adds that env variable so that consul commands continue to work with custom rpc address.
=> Add CONSUL_RPC_ADDR env variable to .bashrc

README.md, defaults/main.yml, meta/main.yml, tasks/install-ui.yml
Added two new variables:
consul_install_nginx: true
consul_install_nginx_config: true
To allow for Consul UI install w/o nginx - I feel it's common for people to have their own roles for nginx and the fact that nginx is installed potentially conflicts with that and was a suprise for me as well. 
Also set to latest Consul version and updated README for that.
=> Allow for Consul UI w/o nginx install

.kitchen.yml, test/integration/helpers/serverspec/Gemfile
- Add a Gemfile to pin the version for net-ssh to < 2.10
- Versions of net-ssh > 2.10 require Ruby 2.x, which causes most
of the existing builds to break. See
test-kitchen/busser-serverspec#37
- Add `nginx_user` to default vars for CentOS builds
- When both nginx roles are included, the variable for `nginx_user`
is carried over from the Debian role which causes the builds
on CentOS to try using the user `www-data`
Here's the output of a test run from master using `kitchen test default-centos7`. You'll see that tasks are run from both nginx roles, and the RHEL one (geerlingguy.nginx) fails because the nginx user is `www-data`.
```
PLAY [localhost] ************************************************************** 
GATHERING FACTS *************************************************************** …
```
=> Fix issues with test kitchen builds

.kitchen.yml, tasks/install.yml, templates/consul.systemd.j2, test/integration/default/serverspec/consul_spec.rb, test/integration/logs/default.yml, test/integration/logs/serverspec/consul_spec.rb, test/integration/logs/serverspec/spec_helper.rb
The `ExecStart` value is executed as a command, not a shell, so we must
pass the command to `/bin/sh -c` in order to properly redirect output
to a logfile.
This also adds a serverspec test to verify log and log directory
permissions as well as that the log size is > 0, which presumably
means that the consul server is actually writing there.
=> Fix systemd logging

README.md, defaults/main.yml, templates/consul.json.j2
Replace the `consul_server_hostname` variable with
`consul_verify_server_hostname`. `consul_server_hostname` can be misleading,
and matching the config setting name is a good convention.
Duplicated logic in the Consul template has also been reduced by including this
option in the same block as the other TLS options.
=> New variable for verify_server_hostname

templates/consul.json.j2
In a previous commit, I mistakenly used the key `join_wan` instead of `start_join_wan`. I overlooked this because I was using the `retry_join_wan` option in my testing.
=> Fix config for start_join_wan

tasks/install.yml, tasks/service.yml
`tasks/service.yml` was restarting the Consul service every time
it ran, regardless of whether or not there were changes. This
is less than optimal, especially on a production system.
Instead, ensure the service is started, and only notify a restart
when the configuration changes.
=> Do not restart Consul every time

defaults/main.yml
0.6.3 is the latest as of today (2016-02-21).
=> Bump default consul version from 0.6.0 to 0.6.3

tasks/install.yml
Previous task was trying to set the CONSUL_RPC_ADDR in the user executing ansible bashrc file. Set this in the consul user's bashrc instead.
=> Set RPC_ADDR in the consul users bashrc

tasks/install-ui.yml
With this change, nginx is allowed to contact the consul service even in enforcing mode.
=> Configure selinux to allow nginx to contact other servers (consul).

meta/main.yml, requirements.yml
The install task needs to install jq, which is not present in the default yum repos.
So this patch add a dependency on the geerlingguy.repo-epel for RedHat family.
=> Add requirements on EPEL repos.

tasks/dnsmasq.yml
Realized my previous PR resulted in a bunch of duplicate lines at EOF. 
This fixes that and also homogenizes the task syntax :smiley:
=> use replace instead of lineinfile to prevent duplicates

tasks/install.yml, templates/consul.systemd.j2
Consul need network online before starting or it would fail.
By the way, there is no reason the service file is 755, and it should be owned by root.
The same asumption could be made (owned by root) for the syvinit script (I can't see no reason to have it owned by the consul user), but I didn't change it because this patch is focused on systemd.
=> Better systemd support.

tasks/install-ui.yml, templates/consul.json.j2
This patch is a proposed fix for #112.
- No need to download and install the ui package
- Need to start the agent with -ui (ui: true in config) instead of ui-dir
It checks on the 6.0.1 version because that is when the ui parameter was introduced in Consul.
=> Change the way we manage UI depending on consul version.

tasks/install-ui.yml, templates/consul-nginx.conf.j2
I had to make these changes for the consul ui to be immediately available after the ansible run finished. here are the variables I'm using for all three local consul nodes i'm using for testing:
```
consul_version: 0.6.3
consul_is_server: true
consul_servers:
- 192.168.13.6
- 192.168.13.7
- 192.168.13.8
consul_datacenter: local
consul_syslog: true
consul_bind_address: "{{ansible_ssh_host}}"
consul_advertise_address: "{{ansible_ssh_host}}"
consul_bootstrap_expect: 3
consul_join_at_start: true
consul_retry_join: true
```
and specifically on the node that is running to ui:
```
consul_is_ui: true
consul_ui_server_name: consul1.dev
```
and my inventory:
```
[consul]
consul1 ansible_ssh_host=192.168.13.6
consul2 ansible_ssh_host=192.168.13.7
consul3 ansible_ssh_host=192.168.13.8
```
i'm curious …
=> Fix nginx root

tasks/install.yml
Ensure the role creates a bashrc file in  `consul_home` if it doesn't exist
=> Create the bashrc file if it doesn't already exist

README.md, defaults/main.yml, handlers/main.yml, tasks/service.yml
In order to allow playbooks to decide what state to leave the consul service in, the handler needs to accept a parameter for `consul_service_state`.
=> Allow consul service state to be overridden

tasks/install.yml
The mode for the init.d script was 0644, which meant the service start
would fail.  Update the script to be executable.
(platform was Amazon Linux, but any initd system should be similar)
=> Update init.d mode to 755

README.md, defaults/main.yml, templates/consul.json.j2
This variable controls whether consul agent/server will leave cluster when it receives SIGINT.
=> Added consul_skip_leave_on_interrupt variable

tasks/install.yml
Since `consul_user` is a system user, I would assume `consul_group` should also be a system group in order to avoid a collision with non-system GIDs.
=> Make consul group a system group

templates/consul.systemd.j2
Systemd automatically logs stdout/error to syslog, so it's a bit redundant to create a separate log file.
https://www.freedesktop.org/software/systemd/man/systemd.exec.html
=> removing shell redirection

templates/consul.conf.j2
After some tinkering, it seems as though on service stop - if you have ```consul_leave_on_terminate``` set to true, this is ignored as the ```service consul stop``` command sends signal 1, not TERM like consul expects for that config to work.
Additionally, if you attempt to do a ```consul leave```, the agent dies and then upstart attempts to kick it on again, which causes it to rejoin the cluster.  This is not desired (afaik).  This pull request doesnt fix that, however it does allow you to just stop the service and have it leave the cluster cleanly.
I've tested both cases - with ```consul_leave_on_terminate```  on and off.  The behavior seems to work as intended now.  However I'm not sure of the downstream impacts of this so could use your input if you have any.
=> On stop service [upstart], send TERM sig

README.md, defaults/main.yml, tasks/install.yml, tasks/service.yml
I can't accept the way upstart is used in this role, I got 1TB of logs during the weekend. So I've moved to [runit](https://github.com/gitinsky/ansible-role-runit) and fixed handler issues.
Here're the variables:
```yml
runit_pre_start_command: "setcap CAP_NET_BIND_SERVICE=+eip /opt/consul/bin/consul"
runit_service_command: "/opt/consul/bin/consul"
runit_service_params: "agent -config-dir /etc/consul.d -config-file=/etc/consul.conf"
runit_service_env:
GOMAXPROCS: "{{ ansible_processor_vcpus }}"
consul_reload_config_handler: runit reload consul
consul_restart_handler: runit restart consul
```
=> Adopted role for use without systemd and upstart

defaults/main.yml, handlers/main.yml, templates/consul.systemd.j2
This PR covers 2 things:
* The service state should be set to the value of the `consul_service_state` variable, but the "_restart consul_" handler should always be `restarted`.
* _systemd_ logs are collected via journald, so the _systemd_ unit shouldn't explicitly forward logs to a file (removing `sh -c` also prevents the service from forking)
=> Improve service status handling and systemd support

defaults/main.yml
The default variable name for disable_update_check setting is incorrect and it causes the following error when running the playbook: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'consul_disable_update_check' is undefined"}. It should be consul_disable_update_check instead of disable_update_check in defaults/main.yml
=> Fix disable_update_check default variable name

handlers/main.yml
Continuation of #133 but rebased to latest master.
=> Reorder handlers so systemd config is reloaded before consul restart

README.md, defaults/main.yml, tasks/main.yml, tasks/service.yml, tasks/services.yml
@savagegus @robbiet480 @benjaminws @msabramo 
This adds support for consul services 
https://www.consul.io/docs/agent/services.html
I am aware of python-consul module (http://docs.ansible.com/ansible/consul_module.html) with ansible version 2.1 it contains bug furthermore requires pip and module above.
=> Add consul services support

templates/consul.systemd.j2
Without this change, running consul on systemd with non-root user would fail with:
```
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Error starting dns server: dns udp setup failed: listen udp 0.0.0.0:53: bind: permission denied
```
=> Add BIND capabilities for consul on systemd

README.md
For CentOS 7 I encountered the following issues:
* Upstart needs to be disabled
* nginx user is not `www-data`
As there is only upstart and systemd to choose from maybe it makes more sense to put this in a single boolean.
This pull request just fixes the example from the README to be a working example. (tested with vagrant and the included `test.yml` file)
=> Fix CentOS 7 example in README

tasks/install-ui.yml
Got error on Ubuntu 16.10:
> FAILED! => {
>     "failed": true,
>     "msg": "The conditional check 'consul_is_ui and consul_install_nginx_config and ansible_selinux.status == \"enabled\"' failed. The error was: error while evaluating conditional (consul_is_ui and consul_install_nginx_config and ansible_selinux.status == \"enabled\"): 'bool object' has no attribute 'status'\n\nThe error appears to have been in '/home/suvitruf/ansible/roles/consul/tasks/install-ui.yml': line 79, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: allow nginx to connect to consul (selinux)\n  ^ here\n"
Aditional check `ansible_selinux is defined` prevents it.
=> additional check to prevent error while checking ansible_selinux.status

defaults/main.yml, tasks/main.yml, templates/consul.conf.j2, vars/Debian.yml, vars/RedHat.yml
The Debian condition for Upstart "start on" was not working for RHEL/CentOS 6 (Consul would not start at boot). It is difficult to tell specifically why not because the Upstart version is so old, but the conditions recommended [here](http://serverfault.com/a/643953/76832) seem to work. The prior values are retained for Debian systems.
=> Make Upstart start/stop conditions configurable and fix RedHat values

templates/consul.conf.j2
Per #182 .
consul was not logging on Ubuntu due to incorrect
redirect syntax in the upstart script.
=> Fix redirect syntax for upstart template.
